force-app/main/default/objects/Account/fields/ATV_Email_Alternativo__c.field-meta.xml
<CustomField>
    <fullName>ATV_Email_Alternativo__c</fullName>
    <label>Email Alternativo</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/ATV_Rango_de_Facturaci_n__c.field-meta.xml
<CustomField>
    <fullName>ATV_Rango_de_Facturaci_n__c</fullName>
    <label>Rango de Facturación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Cat__c.field-meta.xml
<CustomField>
    <fullName>Cat__c</fullName>
    <label>Categoría</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>81</fullName>
                <label>BRONZE</label>
            </value>
            <value>
                <fullName>79</fullName>
                <label>SILVER</label>
            </value>
            <value>
                <fullName>78</fullName>
                <label>GOLD</label>
            </value>
            <value>
                <fullName>80</fullName>
                <label>PLATINUM</label>
            </value>
            <value>
                <fullName>82</fullName>
                <label>EN SONDEO</label>
            </value>
            <value>
                <fullName>83</fullName>
                <label>NO CUALIFICADO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CUIT__c.field-meta.xml
<CustomField>
    <fullName>CUIT__c</fullName>
    <externalId>true</externalId>
    <label>CUIT</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>16</fullName>
                <label>CUSTOMER-0 - CLIENTE PARA REACTIVAR</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>CUSTOMER-1 - ACCIÓN (CERRADO GANADO)</label>
            </value>
            <value>
                <fullName>17</fullName>
                <default>true</default>
                <label>CUSTOMER-2 - CLIENTE EN SONDEO</label>
            </value>
            <value>
                <fullName>CUSTOMER-3 - CLIENTE NO CONTACTADO</fullName>
            </value>
            <value>
                <fullName>21</fullName>
                <label>NO CUALIFICADO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Nombre_Legal__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Legal__c</fullName>
    <label>Nombre Fantasía</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TEL_FONO_ALTERNATIVO__c.field-meta.xml
<CustomField>
    <fullName>TEL_FONO_ALTERNATIVO__c</fullName>
    <label>Teléfono Alternativo</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_Contribuyente__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Contribuyente__c</fullName>
    <label>Tipo de Contribuyente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_Contribuyente</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/GenerateCSVTest.cls
@IsTest
private class GenerateCSVTest {

    @IsTest
    static void testBatchAccountNoTaskCSV() {
		Castle_Flags.updateContactCUIT = true;
        // Crear cuentas de prueba
        List<Account> accList = new List<Account>();
        for(Integer i=1; i<=1; i++){ // Puedes crear varias cuentas
            accList.add(new Account(
                Name = 'Test Account ' + i,
                Estado__c = 'CUSTOMER-3 - CLIENTE NO CONTACTADO', // Valor de picklist válido
                Phone = '809-000-000' + i,
                TEL_FONO_ALTERNATIVO__c = '809-111-111' + i,
                Email__c = 'test' + i + '@test.com',
                ATV_Email_Alternativo__c = 'alt' + i + '@test.com',
                Nombre_Legal__c = 'Legal Name ' + i,
                BillingCountry = 'Dominican Republic',
                BillingState = 'Santo Domingo',
                BillingCity = 'Santo Domingo',
                BillingStreet = 'Calle ' + i,
                BillingPostalCode = '0000' + i,
                CUIT__c =  i,
                Cat__c = '81',
                AccountSource = 'Advertisement',
                Website = 'www.test' + i + '.com',
                Tipo_de_Contribuyente__c = 'Consumidor Final',
                ATV_Rango_de_Facturaci_n__c = '1',
                NumberOfEmployees = i*10,
                Rubro__c = '\N'
            ));
        }
        insert accList;

        // Ejecutar el batch
        Test.startTest();
        Database.executeBatch(new GenerateCSV(), 200);
        Test.stopTest();

        // Verificar que se hayan creado ContentVersion
        List<ContentVersion> cvs = [SELECT Id, Title, PathOnClient FROM ContentVersion WHERE Title LIKE 'AccountNoTask%'];
        System.assert(cvs.size() > 0, 'Se deben haber creado ContentVersion');
    }
}