force-app/main/default/objects/Account/fields/Consumo_actual_total__c.field-meta.xml
<CustomField>
    <fullName>Consumo_actual_total__c</fullName>
    <label>Consumo actual total</label>
    <summarizedField>Consumo_Actual__c.Total__c</summarizedField>
    <summaryForeignKey>Consumo_Actual__c.Cuenta__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Venta_Total_del_Mes__c.field-meta.xml
<CustomField>
    <fullName>Venta_Total_del_Mes__c</fullName>
    <label>Venta Total del Mes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AccountMetricsController.cls
public class AccountMetricsController {
    private final Account account;
    
    public AccountMetricsController(ApexPages.StandardController stdController) {
        if (!Test.isRunningTest()) {
            stdController.addFields(new List<String>{'Consumo_actual_total__c', 'Venta_Total_del_Mes__c'});
        }
        this.account = (Account)stdController.getRecord();
	}

    public Decimal getConsumoActualTotal() {
        return (account.Consumo_actual_total__c != null) ? account.Consumo_actual_total__c.setScale(0) : 0;
    }
    
    public Decimal getVentaTotalDelMes() {
        return (account.Venta_Total_del_Mes__c != null) ? account.Venta_Total_del_Mes__c.setScale(0) : 0;
    }
    
    public String getMarketShare() {
        Decimal consumoTotal = getConsumoActualTotal();
        Decimal ventaTotal = getVentaTotalDelMes();
        
        if (consumoTotal > 0) {
            Decimal marketShare = (ventaTotal / consumoTotal) * 100;
            return marketShare.setScale(0).format() + '%';
        }
        return '0%';
    }
}