force-app/main/default/objects/Account/fields/CUIT__c.field-meta.xml
<CustomField>
    <fullName>CUIT__c</fullName>
    <externalId>true</externalId>
    <label>CUIT</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CUIT__c.field-meta.xml
<CustomField>
    <fullName>CUIT__c</fullName>
    <externalId>true</externalId>
    <label>CUIT</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ID_NetSuite__c.field-meta.xml
<CustomField>
    <fullName>ID_NetSuite__c</fullName>
    <label>ID NetSuite</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BatchDuplicateContactsTest.cls
@isTest	
public class BatchDuplicateContactsTest {
    @isTest
    static void testBatch(){
        Castle_Flags.updateContactCUIT = true;
        Account acc = TEST_Setup.insertAccount('Test');
        acc.ID_NetSuite__c = null;
        insert acc;

        Lead lead = new Lead();
        lead.LastName = 'Test';
        lead.Company = 'Test';
        lead.CUIT__c = 23132121212L;
        insert lead;

		Contact con = TEST_Setup.insertContact(acc.name, acc.Id);
        insert con;
        
        Test.startTest();
        	BatchDuplicateContacts batch = new BatchDuplicateContacts();
			Database.executeBatch(batch, 200);
        Test.stopTest();
    }
}