force-app/main/default/objects/Account/fields/CUIT__c.field-meta.xml
<CustomField>
    <fullName>CUIT__c</fullName>
    <externalId>true</externalId>
    <label>CUIT</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>16</fullName>
                <label>CUSTOMER-0 - CLIENTE PARA REACTIVAR</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>CUSTOMER-1 - ACCIÓN (CERRADO GANADO)</label>
            </value>
            <value>
                <fullName>17</fullName>
                <default>true</default>
                <label>CUSTOMER-2 - CLIENTE EN SONDEO</label>
            </value>
            <value>
                <fullName>CUSTOMER-3 - CLIENTE NO CONTACTADO</fullName>
            </value>
            <value>
                <fullName>21</fullName>
                <label>NO CUALIFICADO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CUIT__c.field-meta.xml
<CustomField>
    <fullName>CUIT__c</fullName>
    <externalId>true</externalId>
    <label>CUIT</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ID_NetSuite__c.field-meta.xml
<CustomField>
    <fullName>ID_NetSuite__c</fullName>
    <label>ID NetSuite</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CloneTasksToLeadsBatchTest.cls
@IsTest
public class CloneTasksToLeadsBatchTest {

    @IsTest
    static void testCloneTasksToLeads() {
        List<Account> accList = new List<Account>();
        for(Integer i = 1; i <= 5; i++){
            String cuitStr = '2000000000' + i;
            accList.add(new Account(
                Name = 'Test Account ' + i,
                Estado__c = 'CUSTOMER-3 - CLIENTE NO CONTACTADO',
                ID_NetSuite__c = null,
                CUIT__c = Decimal.valueOf(cuitStr)
            ));
        }
        insert accList;

        // 2️⃣ Crear leads con el mismo CUIT
        List<Lead> leadList = new List<Lead>();
        for(Integer i = 1; i <= 5; i++){
            String cuitStr = '2000000000' + i;
            leadList.add(new Lead(
                FirstName = 'Lead ' + i,
                LastName = 'Test',
                Company = 'Test Company',
                CUIT__c = Decimal.valueOf(cuitStr)
                //Status = 'Open - Not Contacted'
            ));
        }
        insert leadList;

        List<Task> taskList = new List<Task>();
        for(Account acc : accList){
            taskList.add(new Task(
                Subject = 'Task for ' + acc.Name,
                Status = 'Not Started',
                Priority = 'Normal',
                WhatId = acc.Id
            ));
        }
        insert taskList;

        Test.startTest();
        Database.executeBatch(new CloneTasksToLeadsBatch(), 200);
        Test.stopTest();
    }
}